backend:
  name: git-gateway
  repo: kartikshukla17/finrep-v0
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Author Role", name: "authorRole", widget: "string", required: false }
      - { label: "Author Image", name: "authorImage", widget: "image", required: false }
      - { label: "Categories", name: "categories", widget: "list", default: [] }
      - { label: "Cover Image", name: "coverImage", widget: "image" }
      - { label: "Video URL", name: "videoUrl", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
